/* Generated by GOB (v2.0.12) on Wed Jul 11 13:58:13 2007
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 12

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "phat-lv2-tree-store.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 13 "phat-lv2-tree-store.gob"

static GtkTargetEntry targette = { "galan/CompAction", 0, 234 };

#line 29 "phat-lv2-tree-store.c"
/* self casting macros */
#define SELF(x) PHAT_LV2_TREE_STORE(x)
#define SELF_CONST(x) PHAT_LV2_TREE_STORE_CONST(x)
#define IS_SELF(x) PHAT_IS_LV2_TREE_STORE(x)
#define TYPE_SELF PHAT_TYPE_LV2_TREE_STORE
#define SELF_CLASS(x) PHAT_LV2_TREE_STORE_CLASS(x)

#define SELF_GET_CLASS(x) PHAT_LV2_TREE_STORE_GET_CLASS(x)

/* self typedefs */
typedef PhatLV2TreeStore Self;
typedef PhatLV2TreeStoreClass SelfClass;

/* here are local prototypes */
static void phat_lv2_tree_store_class_init (PhatLV2TreeStoreClass * c) G_GNUC_UNUSED;
static void phat_lv2_tree_store_init (PhatLV2TreeStore * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkTreeStoreClass *parent_class = NULL;

/* Short form macros */
#define self_new phat_lv2_tree_store_new
#define self_lookup phat_lv2_tree_store_lookup
GType
phat_lv2_tree_store_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (PhatLV2TreeStoreClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) phat_lv2_tree_store_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (PhatLV2TreeStore),
			0 /* n_preallocs */,
			(GInstanceInitFunc) phat_lv2_tree_store_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_TREE_STORE, "PhatLV2TreeStore", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((PhatLV2TreeStore *)g_object_new(phat_lv2_tree_store_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static PhatLV2TreeStore * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static PhatLV2TreeStore *
GET_NEW_VARG (const char *first, ...)
{
	PhatLV2TreeStore *ret;
	va_list ap;
	va_start (ap, first);
	ret = (PhatLV2TreeStore *)g_object_new_valist (phat_lv2_tree_store_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
phat_lv2_tree_store_class_init (PhatLV2TreeStoreClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Phat:LV2:Tree:Store::class_init"

	parent_class = g_type_class_ref (GTK_TYPE_TREE_STORE);

}
#undef __GOB_FUNCTION__
#line 20 "phat-lv2-tree-store.gob"
static void 
phat_lv2_tree_store_init (PhatLV2TreeStore * self G_GNUC_UNUSED)
#line 107 "phat-lv2-tree-store.c"
{
#define __GOB_FUNCTION__ "Phat:LV2:Tree:Store::init"
 {
#line 20 "phat-lv2-tree-store.gob"


	    unsigned i;
	    // Setup the columns. Name          IsPlugin       uri
	    GType mytypes[] =  { G_TYPE_STRING, G_TYPE_BOOLEAN, G_TYPE_STRING };
	    gtk_tree_store_set_column_types( GTK_TREE_STORE( self ), 3, mytypes );

	    SLV2World world = slv2_world_new();
	    slv2_world_load_all(world);

	    SLV2Plugins plugins = slv2_world_get_all_plugins(world);

	    //list_plugins(plugins);
	    for (i=0; i < slv2_plugins_size(plugins); ++i) {
		SLV2Plugin p = slv2_plugins_get_at(plugins, i);

		SLV2PluginClass pclass = slv2_plugin_get_class(p); 
		const char *pclass_name = slv2_plugin_class_get_label(pclass);
		const char *plugin_name = slv2_plugin_get_name(p);
		const char *plugin_uri  = slv2_plugin_get_uri(p);
		char *plugin_path = g_strdup_printf( "%s\\%s", pclass_name, plugin_name );

		GtkTreeIter iter;
		if( self_lookup( self, plugin_path, &iter, TRUE ) ) {
		    gtk_tree_store_set( GTK_TREE_STORE(self), &iter, 1, TRUE, 2, plugin_uri, -1 );
		}

		g_free( plugin_path );
	    }

	    slv2_plugins_free(world, plugins);
	    slv2_world_free(world);

	
#line 146 "phat-lv2-tree-store.c"
 }
}
#undef __GOB_FUNCTION__



#line 55 "phat-lv2-tree-store.gob"
GtkTreeModel * 
phat_lv2_tree_store_new (void)
#line 156 "phat-lv2-tree-store.c"
{
#define __GOB_FUNCTION__ "Phat:LV2:Tree:Store::new"
{
#line 55 "phat-lv2-tree-store.gob"
	
	    GtkTreeModel *ret = (GtkTreeModel *) GET_NEW;
	    return GTK_TREE_MODEL(ret);
	}}
#line 165 "phat-lv2-tree-store.c"
#undef __GOB_FUNCTION__

#line 60 "phat-lv2-tree-store.gob"
gboolean 
phat_lv2_tree_store_lookup (PhatLV2TreeStore * self, char * path, GtkTreeIter * iter, gboolean create)
#line 171 "phat-lv2-tree-store.c"
{
#define __GOB_FUNCTION__ "Phat:LV2:Tree:Store::lookup"
#line 60 "phat-lv2-tree-store.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 60 "phat-lv2-tree-store.gob"
	g_return_val_if_fail (PHAT_IS_LV2_TREE_STORE (self), (gboolean )0);
#line 178 "phat-lv2-tree-store.c"
{
#line 60 "phat-lv2-tree-store.gob"
	

		GtkTreeModel *model = GTK_TREE_MODEL( self );

		gchar **splitpath = g_strsplit( path, "\\", -1 );
		int i=0;
		if( ! gtk_tree_model_get_iter_first( model, iter ) ) {

			if( create ) {
				gtk_tree_store_append( self, iter, NULL );
				gtk_tree_store_set( self, iter, 0, splitpath[i], 1, FALSE, -1 );
			} else {
				g_strfreev( splitpath );
				return FALSE;
			}
		}
		while( splitpath[i] ) {
			int found = 0;
			GtkTreeIter olditer;
			do {
				char *name;
				gtk_tree_model_get( model, iter, 0, &name, -1 );
				if( !strcmp( name, splitpath[i] ) ) {
					found = 1;
				}
				free(name);
				olditer = *iter;
			} while( (!found) && gtk_tree_model_iter_next( model, iter ) );
			if( !found ) {
				if( create ) {
					gtk_tree_store_insert_after( self, iter, NULL, &olditer );
					gtk_tree_store_set( self, iter, 0, splitpath[i], 1, FALSE, -1 );
				} else {
					g_strfreev( splitpath );
					return FALSE;
				}
			}
			i++;
			if( splitpath[i] == NULL ) {
				g_strfreev( splitpath );
				return TRUE;
			}

			olditer = *iter;
			if( !gtk_tree_model_iter_children( model, iter, &olditer ) ) {
				if( create ) {
					gtk_tree_store_append( self, iter, &olditer );
					gtk_tree_store_set( self, iter, 0, splitpath[i], 1, FALSE, -1 );
				} else {
					g_strfreev( splitpath );
					return FALSE;
				}
			}

		}

		g_strfreev( splitpath );
		return FALSE;

	}}
#line 241 "phat-lv2-tree-store.c"
#undef __GOB_FUNCTION__
