/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __PHAT_ADJUSTMENT_PRIVATE_H__
#define __PHAT_ADJUSTMENT_PRIVATE_H__

#include "phatadjustment.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _PhatAdjustmentPrivate {
#line 15 "phat-adjustment.gob"
	gfloat rtfloat_copy;
#line 16 "phat-adjustment.gob"
	gfloat * rtfloat;
#line 17 "phat-adjustment.gob"
	gfloat intern;
#line 19 "phat-adjustment.gob"
	gint timeout_source;
#line 22 "phat-adjustment-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
