/* Generated by GOB (v2.0.12) on Thu Jul 12 17:35:23 2007
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 12

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "phatadjustment.h"

#include "phatadjustmentprivate.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) PHAT_ADJUSTMENT(x)
#define SELF_CONST(x) PHAT_ADJUSTMENT_CONST(x)
#define IS_SELF(x) PHAT_IS_ADJUSTMENT(x)
#define TYPE_SELF PHAT_TYPE_ADJUSTMENT
#define SELF_CLASS(x) PHAT_ADJUSTMENT_CLASS(x)

#define SELF_GET_CLASS(x) PHAT_ADJUSTMENT_GET_CLASS(x)

/* self typedefs */
typedef PhatAdjustment Self;
typedef PhatAdjustmentClass SelfClass;

/* here are local prototypes */
static void phat_adjustment_class_init (PhatAdjustmentClass * c) G_GNUC_UNUSED;
static void phat_adjustment_init (PhatAdjustment * self) G_GNUC_UNUSED;
static gboolean phat_adjustment_timeout_func (PhatAdjustment * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkAdjustmentClass *parent_class = NULL;

/* Short form macros */
#define self_new phat_adjustment_new
#define self_timeout_func phat_adjustment_timeout_func
#define self_get_watch_float phat_adjustment_get_watch_float
#define self_set_watch_float phat_adjustment_set_watch_float
GType
phat_adjustment_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (PhatAdjustmentClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) phat_adjustment_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (PhatAdjustment),
			0 /* n_preallocs */,
			(GInstanceInitFunc) phat_adjustment_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_ADJUSTMENT, "PhatAdjustment", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((PhatAdjustment *)g_object_new(phat_adjustment_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static PhatAdjustment * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static PhatAdjustment *
GET_NEW_VARG (const char *first, ...)
{
	PhatAdjustment *ret;
	va_list ap;
	va_start (ap, first);
	ret = (PhatAdjustment *)g_object_new_valist (phat_adjustment_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "Phat:Adjustment::dispose"
	PhatAdjustment *self G_GNUC_UNUSED = PHAT_ADJUSTMENT (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#define timeout_source (self->_priv->timeout_source)
#define VAR timeout_source
	{
#line 20 "phat-adjustment.gob"
	 g_source_remove( VAR ); }
#line 107 "phat-adjustment.c"
	memset(&timeout_source, 0, sizeof(timeout_source));
#undef VAR
#undef timeout_source
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Phat:Adjustment::finalize"
	PhatAdjustment *self G_GNUC_UNUSED = PHAT_ADJUSTMENT (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
}
#undef __GOB_FUNCTION__

static void 
phat_adjustment_class_init (PhatAdjustmentClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Phat:Adjustment::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(PhatAdjustmentPrivate));

	parent_class = g_type_class_ref (GTK_TYPE_ADJUSTMENT);

	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__
#line 22 "phat-adjustment.gob"
static void 
phat_adjustment_init (PhatAdjustment * self G_GNUC_UNUSED)
#line 143 "phat-adjustment.c"
{
#define __GOB_FUNCTION__ "Phat:Adjustment::init"
	self->_priv = G_TYPE_INSTANCE_GET_PRIVATE(self,PHAT_TYPE_ADJUSTMENT,PhatAdjustmentPrivate);
 {
#line 22 "phat-adjustment.gob"

	selfp->intern = 0.0;
	selfp->rtfloat = &( selfp->intern );
	selfp->rtfloat_copy = *( selfp->rtfloat );

	selfp->timeout_source = g_timeout_add( 50, (GSourceFunc) self_timeout_func, (gpointer) self );
    
#line 156 "phat-adjustment.c"
 }
}
#undef __GOB_FUNCTION__



#line 30 "phat-adjustment.gob"
GtkAdjustment * 
phat_adjustment_new (void)
#line 166 "phat-adjustment.c"
{
#define __GOB_FUNCTION__ "Phat:Adjustment::new"
{
#line 30 "phat-adjustment.gob"
	
	GtkAdjustment *ret = (GtkAdjustment *) GET_NEW;
	return GTK_ADJUSTMENT(ret);
    }}
#line 175 "phat-adjustment.c"
#undef __GOB_FUNCTION__

#line 35 "phat-adjustment.gob"
static gboolean 
phat_adjustment_timeout_func (PhatAdjustment * self)
#line 181 "phat-adjustment.c"
{
#define __GOB_FUNCTION__ "Phat:Adjustment::timeout_func"
#line 35 "phat-adjustment.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 35 "phat-adjustment.gob"
	g_return_val_if_fail (PHAT_IS_ADJUSTMENT (self), (gboolean )0);
#line 188 "phat-adjustment.c"
{
#line 35 "phat-adjustment.gob"
	

	gfloat my_copy = *( selfp->rtfloat );
	if( my_copy != selfp->rtfloat_copy ) {
	    selfp->rtfloat_copy = my_copy;
	    gtk_adjustment_set_value( GTK_ADJUSTMENT(self), my_copy );
	}
	return TRUE;
    }}
#line 200 "phat-adjustment.c"
#undef __GOB_FUNCTION__

#line 45 "phat-adjustment.gob"
gfloat * 
phat_adjustment_get_watch_float (PhatAdjustment * self)
#line 206 "phat-adjustment.c"
{
#define __GOB_FUNCTION__ "Phat:Adjustment::get_watch_float"
#line 45 "phat-adjustment.gob"
	g_return_val_if_fail (self != NULL, (gfloat * )0);
#line 45 "phat-adjustment.gob"
	g_return_val_if_fail (PHAT_IS_ADJUSTMENT (self), (gfloat * )0);
#line 213 "phat-adjustment.c"
{
#line 45 "phat-adjustment.gob"
	
	return selfp->rtfloat;
    }}
#line 219 "phat-adjustment.c"
#undef __GOB_FUNCTION__

#line 49 "phat-adjustment.gob"
void 
phat_adjustment_set_watch_float (PhatAdjustment * self, gfloat * watch_float)
#line 225 "phat-adjustment.c"
{
#define __GOB_FUNCTION__ "Phat:Adjustment::set_watch_float"
#line 49 "phat-adjustment.gob"
	g_return_if_fail (self != NULL);
#line 49 "phat-adjustment.gob"
	g_return_if_fail (PHAT_IS_ADJUSTMENT (self));
#line 232 "phat-adjustment.c"
{
#line 49 "phat-adjustment.gob"
	
	selfp->rtfloat = watch_float;
    }}
#line 238 "phat-adjustment.c"
#undef __GOB_FUNCTION__
