/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __TECH_KNOB_PRIVATE_H__
#define __TECH_KNOB_PRIVATE_H__

#include "tech-knob.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _TechKnobPrivate {
#line 46 "tech-knob.gob"
	GList * anim_list;
#line 49 "tech-knob.gob"
	char * anim_name;
#line 52 "tech-knob.gob"
	gint saved_x;
#line 53 "tech-knob.gob"
	gint saved_y;
#line 54 "tech-knob.gob"
	TechKnobState state;
#line 55 "tech-knob.gob"
	gdouble old_value;
#line 56 "tech-knob.gob"
	guint timer;
#line 28 "tech-knob-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
