/* Generated by GOB (v2.0.12)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <gdk/gdk.h>
#include <gtk/gtk.h>

#include <gdk-pixbuf/gdk-pixbuf.h>

#include "config.h"
#include "glib.h"

#include "math.h"
    
#define PIXMAPDIRIFY(filename) \
		(SITE_PKGDATA_DIR G_DIR_SEPARATOR_S "pixmaps" G_DIR_SEPARATOR_S filename)

#define KNOB_SIZE 32
#define SCROLL_DELAY_LENGTH	300
#define MY_PI 3.1415926535897932384626433832795L

#ifndef __TECH_KNOB_H__
#define __TECH_KNOB_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef enum {
	TK_STATE_IDLE,
	TK_STATE_PRESSED,
	TK_STATE_DRAGGING
} TechKnobState;
#define TECH_TYPE_KNOB_STATE tech_knob_state_get_type()
GType tech_knob_state_get_type (void);


/*
 * Type checking and casting macros
 */
#define TECH_TYPE_KNOB	(tech_knob_get_type())
#define TECH_KNOB(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), tech_knob_get_type(), TechKnob)
#define TECH_KNOB_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), tech_knob_get_type(), TechKnob const)
#define TECH_KNOB_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), tech_knob_get_type(), TechKnobClass)
#define TECH_IS_KNOB(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), tech_knob_get_type ())

#define TECH_KNOB_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), tech_knob_get_type(), TechKnobClass)

/* Private structure type */
typedef struct _TechKnobPrivate TechKnobPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_TECH_KNOB__
#define __TYPEDEF_TECH_KNOB__
typedef struct _TechKnob TechKnob;
#endif
struct _TechKnob {
	GtkRange __parent__;
	/*< private >*/
	TechKnobPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _TechKnobClass TechKnobClass;
struct _TechKnobClass {
	GtkRangeClass __parent__;
	GHashTable * pixbuf_cache;
};


/*
 * Public methods
 */
GType	tech_knob_get_type	(void);
GtkWidget * 	tech_knob_new	(void);

/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define TECH_KNOB_PROP_ANIM_NAME(arg)    	"anim_name", __extension__ ({gchar *z = (arg); z;})
#define TECH_KNOB_GET_PROP_ANIM_NAME(arg)	"anim_name", __extension__ ({gchar **z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define TECH_KNOB_PROP_ANIM_NAME(arg)    	"anim_name",(gchar *)(arg)
#define TECH_KNOB_GET_PROP_ANIM_NAME(arg)	"anim_name",(gchar **)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
